import 'server-only'

import SupabaseListener from '../../components/supabase-listener'
import createClient from '../../utils/supabase-server'

export const revalidate = 0

export default async function RootLayout({ children }) {
  const supabase = createClient()

  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <head>
        <title>NextJS 13 example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SupabaseListener accessToken={session?.access_token} />
        {children}
      </body>
    </html>
  )
}
